while True:
  print('jOla')
  print('Ingrese su saludo')
  saludo=input()
  print('escribiste',saludo)
  print('escribe tu nombre:')
  nombre=input('escribe th nombre')
  print('tu nombre es:',nombre)
  apellido=input('escribe tu apellido: ')
  print('tu apellido es:',apellido)